import Head from "next/head";
import Banner from "../components/Banner";
import About from "../components/About";
import Work from "../components/Work";
import Skills from "../components/Skills";
import Education from "../components/Education";
import Contact from "../components/Contact";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div className="font-nunito">
      <Head>
        <title>Israt Jahan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-4 font-serif">
        <Banner />
        <About />
        <Work />
        <Skills />
        <Projects />
        <Education />
        <Contact />
      </div>
    </div>
  );
}
